---
- name: "Add Node.js from Nodesource"
  become: true 
  shell: |
    curl -sL https://deb.nodesource.com/setup_14  | sudo -E bash -

- name: "install Node.js 14"
  become: true 
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
