Description: >
  UdaPeople backend stack.
Parameters:
  Workflow_ID:
        type: String
        default: Workflow_ID=$((1 + RANDOM % 10))
  ID:
    Description: Unique identifier.
    Type: String


Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${Workflow_ID}
      GroupDescription: Allow port 22 and port 3030 and port 9100
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 9100  # For Prometheus
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity 
      ImageId: ami-0557a15b87f6559cf 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}